# Generated by Django 5.1.4 on 2025-01-29 00:19

import django.db.models.deletion
import django_resized.forms
import shop_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=50)),
                (
                    "description",
                    models.TextField(blank=True, db_index=True, max_length=500),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("discount", models.PositiveSmallIntegerField(default=0)),
                ("quantity", models.PositiveSmallIntegerField(default=0)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("archived", models.BooleanField(default=False)),
                (
                    "preview",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format="PNG",
                        keep_meta=True,
                        quality=-1,
                        scale=None,
                        size=[500, 300],
                        upload_to=shop_app.models.product_preview_directory_path,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
