# Generated by Django 5.1.4 on 2025-02-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="name",
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
