# Generated by Django 5.1.4 on 2025-04-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0002_alter_productmodel_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="description",
            field=models.TextField(blank=True, db_index=True, max_length=1000),
        ),
    ]
