# Generated by Django 5.1.4 on 2025-01-29 00:19

import django.db.models.deletion
import django_resized.forms
import profiles_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=30, null=True)),
                ("surname", models.CharField(blank=True, max_length=30, null=True)),
                ("bio", models.TextField(blank=True, max_length=200)),
                (
                    "avatar",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        default="profiles/profile_default/default.png",
                        force_format="PNG",
                        keep_meta=True,
                        null=True,
                        quality=-1,
                        scale=None,
                        size=[500, 300],
                        upload_to=profiles_app.models.profile_preview_directory_path,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
